# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed, jekyll-seo-tag, jekyll-redirect-from]
exclude: ['templates', 'variables.yaml']
mainimage: "/assets/img/thumbnail"

collections:
  - projects

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:       "GitFichas"
description: "Fichas de estudo sobre Git em Português 🇧🇷"
author:      "Jessica Temporal"

