# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed, jekyll-seo-tag, jekyll-redirect-from]
exclude: ['templates', 'variables.yaml']
mainimage: "https://gitfichas.com/assets/img/thumbnail.png"

collections:
  - projects

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:       "GitFichas"
title_en:    "GitStudyCards"
author:      "Jessica Temporal"

include: [.well-known]
